name: flutex_admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  get: ^4.6.5
  http: ^1.2.1
  dio: ^5.4.3+1
  flutter_svg: ^2.0.4
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.15.2
  share_plus: ^10.1.2
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.3.1
  file_picker: ^8.0.3
  connectivity_plus: ^6.1.0
  image_picker: ^1.1.2
  animation_wrappers: ^3.0.0
  introduction_screen: ^3.1.12
  nb_utils: ^7.0.6
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_charts: ^27.1.58
  contained_tab_bar_view: ^0.8.0
  multi_dropdown: ^3.0.1
  date_field: ^5.3.0
  cookie_jar: ^4.0.8
  requests_plus: ^4.8.6
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section
  assets:
    - assets/images/
    - assets/animation/
    - assets/lang/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
